name: ligo
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy=1.26
  - scipy=1.15
  - matplotlib=3.10
  - h5py=3.13
  - decorator=5.1
  - ipykernel=6.29
  - pytest=8.4
  - pytest-cov
  - pip
